** Evercice 1

In [2]:
6+5


ans =

    11



In [3]:
45.78*23.5


ans =

   1.0758e+03



In [4]:
4^5


ans =

        1024



In [5]:
1/3


ans =

    0.3333



In [6]:
format long

In [7]:
1/3


ans =

   0.333333333333333



In [8]:
format short

In [9]:
1/3


ans =

    0.3333



Exercice 2

In [10]:
sin(0.7)


ans =

    0.6442



In [11]:
sind(45)


ans =

    0.7071



In [12]:
help sind

 SIND   Sine of argument in degrees.
    SIND(X) is the sine of the elements of X, expressed in degrees.
    For integers n, sind(n*180) is exactly zero, whereas sin(n*pi)
    reflects the accuracy of the floating point value of pi.
 
    Class support for input X:
       float: double, single
 
    See also ASIND, SIN.

    Documentation for sind
       doc sind

    Other uses of sind

       sym/sind



In [13]:
asin(0.5)


ans =

    0.5236



In [14]:
asind(0.5)


ans =

   30.0000



In [15]:
sqrt(3)


ans =

    1.7321



In [16]:
1.7321^2


ans =

    3.0002



In [17]:
sqrt(3)


ans =

    1.7321



In [18]:
ans


ans =

    1.7321



In [19]:
ans^2


ans =

    3.0000



In [20]:
cos(3/4*pi),log(5.6),exp(2.3),tan(pi/4)


ans =

   -0.7071


ans =

    1.7228


ans =

    9.9742


ans =

    1.0000



In [21]:
cos(3/4*pi),log(5.6);exp(2.3),tan(pi/4);


ans =

   -0.7071


ans =

    9.9742



EXERCICE 3

In [22]:
c=6


c =

     6



In [23]:
c==3


ans =

  logical

   0



In [24]:
c>3


ans =

  logical

   1



In [25]:
c<4


ans =

  logical

   0



In [26]:
~(c<4)


ans =

  logical

   1



In [27]:
(c>3)&(c<4)


ans =

  logical

   0



In [28]:
(c>3)&(c<8)


ans =

  logical

   1



In [29]:
(c>3)|(c<4)


ans =

  logical

   1



EXERCICE 4

In [30]:
1 + i


ans =

   1.0000 + 1.0000i



In [31]:
1 +j


ans =

   1.0000 + 1.0000i



In [33]:
3 - 5i


ans =

   3.0000 - 5.0000i



In [34]:
3 - 5*i 


ans =

   3.0000 - 5.0000i



In [35]:
3 - 5 i

Invalid expression. Check for missing multiplication operator, missing or
unbalanced delimiters, or other syntax error. To construct matrices, use
brackets instead of parentheses.



In [36]:
i*(i + 2)


ans =

  -1.0000 + 2.0000i



In [43]:
z=3+5i;

In [44]:
module=abs(z)


module =

    5.8310



In [45]:
conjugue=conj(z)


conjugue =

   3.0000 - 5.0000i



In [46]:
real(conjugue)


ans =

     3



In [47]:
imag(conjugue)


ans =

    -5



In [48]:
argument=angle(z)


argument =

    1.0304



EXERCICE 5

In [49]:
x=2.5;y=3.1;r=x^2+y^2


r =

   15.8600



In [50]:
x


x =

    2.5000



In [51]:
y


y =

    3.1000



In [52]:
rayon=3.4


rayon =

    3.4000



In [53]:
Rayon=4.5e-3


Rayon =

    0.0045



In [54]:
z_1=3.4+5.3i


z_1 =

   3.4000 + 5.3000i



In [55]:
nom="dupont"


nom = 

    "dupont"



In [56]:
chiffre="5"


chiffre = 

    "5"



EXERCICE 6

In [57]:
who


Your variables are:

Rayon     c         module    rayon     z         
ans       chiffre   nom       x         z_1       
argument  conjugue  r         y         



In [58]:
whos

  Name          Size            Bytes  Class     Attributes

  Rayon         1x1                 8  double              
  ans           1x1                 8  double              
  argument      1x1                 8  double              
  c             1x1                 8  double              
  chiffre       1x1               150  string              
  conjugue      1x1                16  double    complex   
  module        1x1                 8  double              
  nom           1x1               150  string              
  r             1x1                 8  double              
  rayon         1x1                 8  double              
  x             1x1                 8  double              
  y             1x1                 8  double              
  z             1x1                16  double    complex   
  z_1           1x1                16  double    complex   



In [59]:
clear Rayon

In [60]:
whos

  Name          Size            Bytes  Class     Attributes

  ans           1x1                 8  double              
  argument      1x1                 8  double              
  c             1x1                 8  double              
  chiffre       1x1               150  string              
  conjugue      1x1                16  double    complex   
  module        1x1                 8  double              
  nom           1x1               150  string              
  r             1x1                 8  double              
  rayon         1x1                 8  double              
  x             1x1                 8  double              
  y             1x1                 8  double              
  z             1x1                16  double    complex   
  z_1           1x1                16  double    complex   



In [61]:
save("mem1.mat")

In [62]:
clear

In [63]:
whos

In [64]:
load("mem1.mat")

In [65]:
whos

  Name          Size            Bytes  Class     Attributes

  ans           1x1                 8  double              
  argument      1x1                 8  double              
  c             1x1                 8  double              
  chiffre       1x1               150  string              
  conjugue      1x1                16  double    complex   
  module        1x1                 8  double              
  nom           1x1               150  string              
  r             1x1                 8  double              
  rayon         1x1                 8  double              
  x             1x1                 8  double              
  y             1x1                 8  double              
  z             1x1                16  double    complex   
  z_1           1x1                16  double    complex   



EXERCICE 7

In [66]:
clear

In [67]:
v1=[3.4,5.6,7.8]


v1 =

    3.4000    5.6000    7.8000



In [68]:
v1c=[3.4;5.6;7.8]


v1c =

    3.4000
    5.6000
    7.8000



In [69]:
whos

  Name      Size            Bytes  Class     Attributes

  v1        1x3                24  double              
  v1c       3x1                24  double              



In [70]:
v1==v1c


ans =

  3x3 logical array

   1   0   0
   0   1   0
   0   0   1



In [72]:
v2=v1c'


v2 =

    3.4000    5.6000    7.8000



In [73]:
v1==v2


ans =

  1x3 logical array

   1   1   1



In [74]:
help transpose

 .' Transpose.
    X.' is the non-conjugate transpose.
 
    B = TRANSPOSE(A) is called for the syntax A.' when A is an object.
 
    See <a href="matlab:helpview('matlab','MATLAB_OPS')">MATLAB Operators and Special Characters</a> for more details.
 
    See also CTRANSPOSE, PERMUTE, PAGETRANSPOSE.

    Documentation for transpose
       doc transpose

    Other uses of transpose

       categorical/transpose
       matlab.mixin.indexing.RedefinesParen/transpose
       sym/transpose
       symbolic/transpose



In [75]:
transpose(v1c)


ans =

    3.4000    5.6000    7.8000



EXERCICE 8

In [76]:
v1(1)


ans =

    3.4000



In [77]:
v1(3)


ans =

    7.8000



In [78]:
v1(end)


ans =

    7.8000



EXERCICE 9

In [79]:
1:5


ans =

     1     2     3     4     5



In [80]:
1.1:5.5


ans =

    1.1000    2.1000    3.1000    4.1000    5.1000



In [81]:
1:0.25:5


ans =

  Columns 1 through 7

    1.0000    1.2500    1.5000    1.7500    2.0000    2.2500    2.5000

  Columns 8 through 14

    2.7500    3.0000    3.2500    3.5000    3.7500    4.0000    4.2500

  Columns 15 through 17

    4.5000    4.7500    5.0000



In [82]:
v3=[1:0.25:5]


v3 =

  Columns 1 through 7

    1.0000    1.2500    1.5000    1.7500    2.0000    2.2500    2.5000

  Columns 8 through 14

    2.7500    3.0000    3.2500    3.5000    3.7500    4.0000    4.2500

  Columns 15 through 17

    4.5000    4.7500    5.0000



In [83]:
v4=[1:-0.1:-1]


v4 =

  Columns 1 through 7

    1.0000    0.9000    0.8000    0.7000    0.6000    0.5000    0.4000

  Columns 8 through 14

    0.3000    0.2000    0.1000         0   -0.1000   -0.2000   -0.3000

  Columns 15 through 21

   -0.4000   -0.5000   -0.6000   -0.7000   -0.8000   -0.9000   -1.0000



EXERCICE 10

In [84]:
v3(9)


ans =

     3



In [85]:
v3([5,6,7,8,9])


ans =

    2.0000    2.2500    2.5000    2.7500    3.0000



In [86]:
v3([5:9])


ans =

    2.0000    2.2500    2.5000    2.7500    3.0000



In [87]:
sv3=v3([5:9])


sv3 =

    2.0000    2.2500    2.5000    2.7500    3.0000



In [88]:
whos

  Name      Size            Bytes  Class     Attributes

  ans       1x5                40  double              
  sv3       1x5                40  double              
  v1        1x3                24  double              
  v1c       3x1                24  double              
  v2        1x3                24  double              
  v3        1x17              136  double              
  v4        1x21              168  double              



In [89]:
sv31=v3([5:2:13])


sv31 =

    2.0000    2.5000    3.0000    3.5000    4.0000



In [90]:
sv1c=v1c([2:end])


sv1c =

    5.6000
    7.8000



EXERCICE 11

In [91]:
help length

 LENGTH   Length of vector.
    LENGTH(X) returns the length of vector X.  It is equivalent
    to MAX(SIZE(X)) for non-empty arrays and 0 for empty ones.
   
    See also NUMEL.

    Documentation for length
       doc length

    Other uses of length

       categorical/length
       containers.Map/length
       dataset/length
       dictionary/length
       matlab.mixin.indexing.RedefinesParen/length
       serial/length
       tall/length
       tscollection/length



In [92]:
length(v1)


ans =

     3



In [93]:
length(v1c)


ans =

     3



In [94]:
help size

 SIZE   Size of array.  
    D = SIZE(X), for M-by-N matrix X, returns the two-element row vector
    D = [M,N] containing the number of rows and columns in the matrix.
    For N-D arrays, SIZE(X) returns a 1-by-N vector of dimension lengths.
    Trailing singleton dimensions are ignored.
 
    [M,N] = SIZE(X) for matrix X, returns the number of rows and columns in
    X as separate output variables. 
    
    [M1,M2,M3,...,MN] = SIZE(X) for N>1 returns the sizes of the first N 
    dimensions of the array X.  If the number of output arguments N does
    not equal NDIMS(X), then for:
 
    N > NDIMS(X), SIZE returns ones in the "extra" variables, i.e., outputs
                  NDIMS(X)+1 through N.
    N < NDIMS(X), MN contains the product of the sizes of dimensions N
                  through NDIMS(X).
 
    M = SIZE(X,DIM) returns the lengths of the specified dimensions in a 
    row vector. DIM can be a scalar or vector of dimensions. For example, 
    SIZE(X,1) returns the number 

In [95]:
size(v1)


ans =

     1     3



In [96]:
size(v1c)


ans =

     3     1



EXERCICE 12

In [97]:
clear all

In [98]:
who

In [99]:
a0=[1,2,3.2;4,2,7]


a0 =

    1.0000    2.0000    3.2000
    4.0000    2.0000    7.0000



In [103]:
a1=a0';

In [104]:
a1


a1 =

    1.0000    4.0000
    2.0000    2.0000
    3.2000    7.0000



In [105]:
m1=[1,3;6,7]


m1 =

     1     3
     6     7



In [106]:
m2=[1,3,4;...
     4,5,6]


m2 =

     1     3     4
     4     5     6



In [107]:
tm1=m1'


tm1 =

     1     6
     3     7



In [108]:
tm2=transpose(m2)


tm2 =

     1     4
     3     5
     4     6



In [109]:
m3=[4.5,3,6;7.1,4,1;5,8,9.4]


m3 =

    4.5000    3.0000    6.0000
    7.1000    4.0000    1.0000
    5.0000    8.0000    9.4000



EXERCICE 13

In [110]:
m3(3,1)


ans =

     5



In [111]:
m3(3,3)


ans =

    9.4000



In [112]:
vm3=m3(1,[1:end])


vm3 =

    4.5000    3.0000    6.0000



In [113]:
vm31=m3([1:end],2)


vm31 =

     3
     4
     8



In [114]:
% Equivalence

In [115]:
vm31=m3(:,2)


vm31 =

     3
     4
     8



In [116]:
sm3=m3(2:3,2:3)



sm3 =

    4.0000    1.0000
    8.0000    9.4000



EXERCICE 14

In [117]:
size(m2)


ans =

     2     3



In [118]:
size(tm2)


ans =

     3     2



In [119]:
size(m3)


ans =

     3     3



In [122]:
size(a0,1)


ans =

     2



In [123]:
size(a0,2)


ans =

     3



EXERCICE 15

In [125]:
m3


m3 =

    4.5000    3.0000    6.0000
    7.1000    4.0000    1.0000
    5.0000    8.0000    9.4000



In [124]:
vd1=diag(m3)


vd1 =

    4.5000
    4.0000
    9.4000



In [126]:
vd2=diag(m3,1)


vd2 =

     3
     1



In [127]:
vd3=diag(m3,-1)


vd3 =

    7.1000
    8.0000



In [128]:
m4=diag([1,2,3])


m4 =

     1     0     0
     0     2     0
     0     0     3



In [129]:
m5=diag([1,2,3],1)


m5 =

     0     1     0     0
     0     0     2     0
     0     0     0     3
     0     0     0     0



EXERCICE 16

In [130]:
m6=zeros(5)


m6 =

     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0



In [131]:
v6=zeros(1,6)


v6 =

     0     0     0     0     0     0



In [132]:
m61=zeros(3,2)


m61 =

     0     0
     0     0
     0     0



In [133]:
m7=ones(4)


m7 =

     1     1     1     1
     1     1     1     1
     1     1     1     1
     1     1     1     1



In [134]:
v7=ones(4,1)


v7 =

     1
     1
     1
     1



In [135]:
m71=ones(2,3)


m71 =

     1     1     1
     1     1     1



In [136]:
m8=rand(4)


m8 =

    0.8147    0.6324    0.9575    0.9572
    0.9058    0.0975    0.9649    0.4854
    0.1270    0.2785    0.1576    0.8003
    0.9134    0.5469    0.9706    0.1419



In [137]:
m9=eye(5)


m9 =

     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0
     0     0     0     1     0
     0     0     0     0     1



EXERCICE 17

In [138]:
v1=[3.4,5.6,7.8]


v1 =

    3.4000    5.6000    7.8000



In [139]:
v11=v1+[3:5]


v11 =

    6.4000    9.6000   12.8000



In [140]:
v12=pi*v11


v12 =

   20.1062   30.1593   40.2124



In [142]:
v1*v1

Error using *
Incorrect dimensions for matrix multiplication. Check that the number of
columns in the first matrix matches the number of rows in the second matrix. To
operate on each element of the matrix individually, use TIMES (.*) for
elementwise multiplication.



In [143]:
v1*v1'


ans =

  103.7600



In [144]:
v1'*v1


ans =

   11.5600   19.0400   26.5200
   19.0400   31.3600   43.6800
   26.5200   43.6800   60.8400



In [145]:
v1+v1'


ans =

    6.8000    9.0000   11.2000
    9.0000   11.2000   13.4000
   11.2000   13.4000   15.6000



In [146]:
dot(v1,[3,4,5])


ans =

   71.6000



EXERCICE 18

In [147]:
A=rand(length(v1))


A =

    0.4218    0.9595    0.8491
    0.9157    0.6557    0.9340
    0.7922    0.0357    0.6787



In [148]:
y=A*v1

Error using *
Incorrect dimensions for matrix multiplication. Check that the number of
columns in the first matrix matches the number of rows in the second matrix. To
operate on each element of the matrix individually, use TIMES (.*) for
elementwise multiplication.



In [149]:
y=A*v1'


y =

   13.4304
   14.0708
    8.1876



In [151]:
y=rand(5)*v1'

Error using *
Incorrect dimensions for matrix multiplication. Check that the number of
columns in the first matrix matches the number of rows in the second matrix. To
operate on each element of the matrix individually, use TIMES (.*) for
elementwise multiplication.



In [152]:
m3*rand(size(m3))


ans =

    3.6712    6.3020    8.7929
    3.5223    6.6187    8.7897
    5.6829   10.1721   14.0037



EXERCICE 19

In [153]:
v1


v1 =

    3.4000    5.6000    7.8000



In [154]:
v1e=v1.*[1:3]


v1e =

    3.4000   11.2000   23.4000



In [155]:
v11e=v1e./v1


v11e =

     1     2     3



In [156]:
v12e=v1.^2.5


v12e =

   21.3156   74.2113  169.9169



In [157]:
m11=2*ones(3)


m11 =

     2     2     2
     2     2     2
     2     2     2



In [158]:
m11.^(1/3)


ans =

    1.2599    1.2599    1.2599
    1.2599    1.2599    1.2599
    1.2599    1.2599    1.2599



In [159]:
m11.^m3


ans =

   22.6274    8.0000   64.0000
  137.1870   16.0000    2.0000
   32.0000  256.0000  675.5881



In [160]:
m11./m3


ans =

    0.4444    0.6667    0.3333
    0.2817    0.5000    2.0000
    0.4000    0.2500    0.2128



In [161]:
m11.*m3


ans =

    9.0000    6.0000   12.0000
   14.2000    8.0000    2.0000
   10.0000   16.0000   18.8000



In [162]:
sin(pi*m3)


ans =

    1.0000    0.0000   -0.0000
   -0.3090   -0.0000    0.0000
    0.0000   -0.0000   -0.9511



In [163]:
m11.*m3.*sin(pi*m3)


ans =

    9.0000    0.0000   -0.0000
   -4.3880   -0.0000    0.0000
    0.0000   -0.0000  -17.8799



EXERCICE 20

In [164]:
help norm

 NORM   Vector and matrix norms.
    N = NORM(V) returns the 2-norm or Euclidean norm of the vector V and is
    the same as NORM(V,2).
 
    N = NORM(V,p) returns the generalized vector p-norm.
    * If p is a positive real scalar, the p-norm is defined as
      SUM(ABS(V).^p)^(1/p).
    * If p = Inf, then N is the largest element of ABS(V).
    * If p = -Inf, then N is the smallest element of ABS(V).
 
    N = NORM(M) returns the 2-norm of the matrix M, which is same as
    NORM(M,2), and is defined by the largest singular value.
 
    N = NORM(M,p) returns the p-norm of the matrix M, where p is 1, 2, or
    Inf.
    * If p = 1, then N is the maximum absolute column sum in M.
    * If p = 2, then N is the maximum singular value of M.
    * If p = Inf, then N is the maximum absolute row sum of M.
 
    N = NORM(X,"fro") returns the Frobenius norm of any numeric array X.
    Notice that the Frobenius norm for vectors is equivalent to the 2-norm.
    For N-D arrays, only the Frobenius n

In [165]:
v1


v1 =

    3.4000    5.6000    7.8000



In [166]:
norm(v1)


ans =

   10.1863



In [167]:
m3


m3 =

    4.5000    3.0000    6.0000
    7.1000    4.0000    1.0000
    5.0000    8.0000    9.4000



In [168]:
norm(m3)


ans =

   16.6823



In [169]:
rank(m3)


ans =

     3



In [170]:
trace(m3)


ans =

   17.9000



In [171]:
det(m3)


ans =

  168.7800



In [172]:
eig(m3)


ans =

  16.1575 + 0.0000i
   0.8712 + 3.1124i
   0.8712 - 3.1124i



In [173]:
inv(m3)


ans =

    0.1754    0.1173   -0.1244
   -0.3658    0.0729    0.2257
    0.2180   -0.1244   -0.0196



In [174]:
cond(m3)


ans =

    8.7366



EXERCICE 21

In [175]:
f=[1;2;3]


f =

     1
     2
     3



In [176]:
x1=m3\f


x1 =

    0.0367
    0.4572
   -0.0895



In [177]:
x2=inv(m3)*f


x2 =

    0.0367
    0.4572
   -0.0895



In [178]:
g=[1,2,3]


g =

     1     2     3



In [179]:
g==f'


ans =

  1x3 logical array

   1   1   1



In [182]:
inv(m3)*g

Error using *
Incorrect dimensions for matrix multiplication. Check that the number of
columns in the first matrix matches the number of rows in the second matrix. To
operate on each element of the matrix individually, use TIMES (.*) for
elementwise multiplication.



EXERCICE 22

In [183]:
v3=[1:0.25:5]


v3 =

  Columns 1 through 7

    1.0000    1.2500    1.5000    1.7500    2.0000    2.2500    2.5000

  Columns 8 through 14

    2.7500    3.0000    3.2500    3.5000    3.7500    4.0000    4.2500

  Columns 15 through 17

    4.5000    4.7500    5.0000



In [184]:
sum(v3)


ans =

    51



In [185]:
v1


v1 =

    3.4000    5.6000    7.8000



In [186]:
sum(v1)


ans =

   16.8000



In [187]:
prod(v1)


ans =

  148.5120



In [188]:
prod(v3)


ans =

   2.3602e+07



In [189]:
sum(m3)


ans =

   16.6000   15.0000   16.4000



In [190]:
m3


m3 =

    4.5000    3.0000    6.0000
    7.1000    4.0000    1.0000
    5.0000    8.0000    9.4000



In [191]:
prod(m3)


ans =

  159.7500   96.0000   56.4000



EXERCICE 23

In [193]:
v3


v3 =

  Columns 1 through 7

    1.0000    1.2500    1.5000    1.7500    2.0000    2.2500    2.5000

  Columns 8 through 14

    2.7500    3.0000    3.2500    3.5000    3.7500    4.0000    4.2500

  Columns 15 through 17

    4.5000    4.7500    5.0000



In [192]:
i0=find(v3==2.75)


i0 =

     8



In [194]:
v3(i0)


ans =

    2.7500



In [195]:
i1=find(v3<=2)


i1 =

     1     2     3     4     5



In [196]:
v3(i1)


ans =

    1.0000    1.2500    1.5000    1.7500    2.0000



In [197]:
vv3=sin(pi*v3)


vv3 =

  Columns 1 through 7

    0.0000   -0.7071   -1.0000   -0.7071   -0.0000    0.7071    1.0000

  Columns 8 through 14

    0.7071    0.0000   -0.7071   -1.0000   -0.7071   -0.0000    0.7071

  Columns 15 through 17

    1.0000    0.7071    0.0000



In [198]:
i2=find(vv3>=sqrt(2)/2)


i2 =

     7     8    14    15    16



In [199]:
vv3(i2)


ans =

    1.0000    0.7071    0.7071    1.0000    0.7071

